In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import scipy.stats as stats
import statsmodels.api as sm
from scipy.stats import chi2_contingency

# Load Datasets
df_clients = pd.read_csv('../data/raw_data_txt/df_final_demo.txt', sep=',')
df_web_1 = pd.read_csv('../data/raw_data_txt/df_final_web_data_pt_1.txt', sep=',')
df_web_2 = pd.read_csv('../data/raw_data_txt/df_final_web_data_pt_2.txt', sep=',')
df_groups = pd.read_csv('../data/raw_data_txt/df_final_experiment_clients.txt', sep=',')
# Merge Logs
df_logs = pd.concat([df_web_1, df_web_2], ignore_index=True)

In [2]:
# EDA: Shape, Head and Dtype of demo (Client Profile)
print(f"Shape: {df_clients.shape[0]} rows × {df_clients.shape[1]} columns\nHead:\n{df_clients.head(3)} \n\nData Types:\n{df_clients.dtypes} \n\nNumerical Columns: {df_clients.select_dtypes(include=['int64', 'float64']).columns.tolist()} \n\nNulls for Numerical Columns:\n{df_clients.select_dtypes(include=['int64', 'float64']).isnull().sum()}\n\nNulls for Categorical Columns:\n{df_clients.select_dtypes(include=['object']).isnull().sum()}\n\nUniques For Categorical Columns:\n {df_clients.select_dtypes(include=['object']).value_counts()}\n\nDuplicates for Numerical: {df_clients.select_dtypes(include=['int64', 'float64']).duplicated().sum()} \n\nUniques For Numerical Columns:\n{df_clients.select_dtypes(include=['int64', 'float64']).nunique()}")

Shape: 70609 rows × 9 columns
Head:
   client_id  clnt_tenure_yr  clnt_tenure_mnth  clnt_age gendr  num_accts  \
0     836976             6.0              73.0      60.5     U        2.0
1    2304905             7.0              94.0      58.0     U        2.0
2    1439522             5.0              64.0      32.0     U        2.0

         bal  calls_6_mnth  logons_6_mnth
0   45105.30           6.0            9.0
1  110860.30           6.0            9.0
2   52467.79           6.0            9.0

Data Types:
client_id             int64
clnt_tenure_yr      float64
clnt_tenure_mnth    float64
clnt_age            float64
gendr                object
num_accts           float64
bal                 float64
calls_6_mnth        float64
logons_6_mnth       float64
dtype: object

Numerical Columns: ['client_id', 'clnt_tenure_yr', 'clnt_tenure_mnth', 'clnt_age', 'num_accts', 'bal', 'calls_6_mnth', 'logons_6_mnth']

Nulls for Numerical Columns:
client_id            0
clnt_tenure_yr      14
clnt_tenure_mnth    14
clnt_age            15
num_accts           14
bal                 14
calls_6_mnth        14
logons_6_mnth       14
dtype: int64

Nulls for Categorical Columns:
gendr    14
dtype: int64

Uniques For Categorical Columns:
 gendr
U        24122
M        23724
F        22746
X            3
Name: count, dtype: int64

Duplicates for Numerical: 0

Uniques For Numerical Columns:
client_id           70609
clnt_tenure_yr         54
clnt_tenure_mnth      482
clnt_age              165
num_accts               8
bal                 70328
calls_6_mnth            8
logons_6_mnth           9
dtype: int64

In [3]:
# EDA: Shape, Head and Dtype of Web Data (Web Activity Logs)
print(f"Shape: {df_logs.shape[0]} rows × {df_logs.shape[1]} columns\nHead:\n{df_logs.head(3)} \n\nData Types:\n{df_logs.dtypes} \n\nNumerical Columns: {df_logs.select_dtypes(include=['int64', 'float64']).columns.tolist()} \n\nNulls for Numerical Columns:\n{df_logs.select_dtypes(include=['int64', 'float64']).isnull().sum()}\n\nNulls for Categorical Columns:\n{df_logs.select_dtypes(include=['object']).isnull().sum()}\n\nUniques For Categorical Columns:\n {df_logs.select_dtypes(include=['object']).value_counts()}\n\nDuplicates for Numerical: {df_logs.select_dtypes(include=['int64', 'float64']).duplicated().sum()} \n\nUniques For Numerical Columns:\n{df_logs.select_dtypes(include=['int64', 'float64']).nunique()}")

Shape: 755405 rows × 5 columns
Head:
   client_id            visitor_id                      visit_id process_step  \
0    9988021  580560515_7732621733  781255054_21935453173_531117       step_3
1    9988021  580560515_7732621733  781255054_21935453173_531117       step_2
2    9988021  580560515_7732621733  781255054_21935453173_531117       step_3

             date_time
0  2017-04-17 15:27:07
1  2017-04-17 15:26:51
2  2017-04-17 15:19:22

Data Types:
client_id        int64
visitor_id      object
visit_id        object
process_step    object
date_time       object
dtype: object

Numerical Columns: ['client_id']

Nulls for Numerical Columns:
client_id    0
dtype: int64

Nulls for Categorical Columns:
visitor_id      0
visit_id        0
process_step    0
date_time       0
dtype: int64

Uniques For Categorical Columns:
 visitor_id             visit_id                      process_step  date_time
538182101_79929060847  273092462_14025162492_252779  start         2017-05-02 10:05:44    16
78799102_14329268381   602953935_48759866176_238903  start         2017-05-02 10:31:57    16
542238919_69240463681  465085750_45266584944_493886  start         2017-05-02 10:59:42    16
780189529_68744403580  961878360_85895454962_607105  start         2017-05-02 10:23:39    16
115360897_69382200220  987081616_72285109481_4050    start         2017-05-02 10:28:41    16
                                                                                          ..
999995931_60089148022  404770421_68000209065_385549  start         2017-04-05 12:22:14     1
                                                     step_1        2017-04-05 12:22:22     1
                                                     step_2        2017-04-05 12:23:03     1
                                                                   2017-04-05 12:25:33     1
                                                     step_3        2017-04-05 12:25:37     1
Name: count, Length: 744641, dtype: int64

Duplicates for Numerical: 635248

Uniques For Numerical Columns:
client_id    120157
dtype: int64

In [4]:
# EDA: Shape, Head and Dtype of Experiment (Test/Control Assignments)
print(f"Shape: {df_groups.shape[0]} rows × {df_groups.shape[1]} columns\nHead:\n{df_groups.head(3)} \n\nData Types:\n{df_groups.dtypes} \n\nNumerical Columns: {df_groups.select_dtypes(include=['int64', 'float64']).columns.tolist()} \n\nNulls for Numerical Columns:\n{df_groups.select_dtypes(include=['int64', 'float64']).isnull().sum()}\n\nNulls for Categorical Columns:\n{df_groups.select_dtypes(include=['object']).isnull().sum()}\nUniques For Categorical Columns:\n {df_groups.select_dtypes(include=['object']).value_counts()}\n\nDuplicates for Numerical: {df_groups.select_dtypes(include=['int64', 'float64']).duplicated().sum()} \n\nUniques For Numerical Columns:\n{df_groups.select_dtypes(include=['int64', 'float64']).nunique()}")

Shape: 70609 rows × 2 columns
Head:
   client_id Variation
0    9988021      Test
1    8320017      Test
2    4033851   Control

Data Types:
client_id     int64
Variation    object
dtype: object

Numerical Columns: ['client_id']

Nulls for Numerical Columns:
client_id    0
dtype: int64

Nulls for Categorical Columns:
Variation    20109
dtype: int64
Uniques For Categorical Columns:
 Variation
Test         26968
Control      23532
Name: count, dtype: int64

Duplicates for Numerical: 0

Uniques For Numerical Columns:
client_id    70609
dtype: int64

In [5]:
### Data Clean ### 

# Clean Clients
df_clients_clean = df_clients.dropna().copy()
df_clients_clean.loc[:, 'clnt_tenure_mnth'] = df_clients_clean['clnt_tenure_yr'] * 12
tenure_mismatch = df_clients_clean[
    df_clients_clean['clnt_tenure_yr'] * 12 != df_clients_clean['clnt_tenure_mnth']
]
print(f"==> Tenure mismatches fixed: {len(tenure_mismatch)} remain")

# Clean Groups
df_groups_clean = df_groups.copy()

# Clean Logs and Filter by Date
df_logs = df_logs.copy()
df_logs['date_time'] = pd.to_datetime(df_logs['date_time'])

# Keep only logs within experiment window
df_logs = df_logs[
    (df_logs['date_time'] >= '2017-03-15') &
    (df_logs['date_time'] <= '2017-06-20')
]
step_counts = df_logs['process_step'].value_counts()
print(f"==> Funnel steps (logs within experiment window): {step_counts.to_dict()}")

# Join Datasets
df_logs_groups = df_logs.merge(
    df_groups_clean[['client_id','Variation']],
    on='client_id',
    how='left'
)
df_full = df_logs_groups.merge(
    df_clients_clean,
    on='client_id',
    how='left'
)

# Validation Checks of This Dataset
print(f"==> df_full shape: {df_full.shape}, unique clients: {df_full['client_id'].nunique()}")
print(f"==> Variation distribution: {df_full['Variation'].value_counts(dropna=False).to_dict()}")
print(f"==> Confirmations in df_full: {(df_full['process_step']=='confirm').sum()}")
print("Sample covers from", df_full['date_time'].min(), "to", df_full['date_time'].max())

# Validation: distinct visit_id count per client
visit_counts = (
    df_full
    .groupby('client_id')['visit_id']
    .nunique()
    .reset_index(name='n_visits')
)
print("\nVisits per client distribution:\n",
      visit_counts['n_visits'].value_counts().sort_index().to_dict())
multi = (visit_counts['n_visits'] > 1).sum()
print(f"Clients with >1 visit_id: {multi}")

# Step Counts by Variation (with Totals)
step_by_var = (
    df_full[df_full['Variation'].notna()]
    .groupby(['Variation','process_step'])['client_id']
    .nunique()
    .unstack(fill_value=0)
)
step_by_var.loc['Total'] = step_by_var.sum()
print("\n==> Step counts by groups assigment:")
print(step_by_var)

# Save to pickle: full structure, fast to load
df_full.to_pickle("../data/clean_data_txt/df_full.pkl")

==> Tenure mismatches fixed: 0 remain
==> Funnel steps (logs within experiment window): {'start': 241320, 'step_1': 161459, 'step_2': 131710, 'step_3': 111241, 'confirm': 101843}
==> df_full shape: (747573, 14), unique clients: 119074
==> Variation distribution: {nan: 428052, 'Test': 177114, 'Control': 142407}
==> Confirmations in df_full: 101843
Sample covers from 2017-03-15 00:03:03 to 2017-06-19 23:59:59

Visits per client distribution:
 {1: 91572, 2: 20702, 3: 4604, 4: 1309, 5: 463, 6: 191, 7: 93, 8: 64, 9: 32, 10: 17, 11: 5, 12: 10, 13: 4, 14: 1, 15: 1, 16: 1, 17: 3, 18: 1, 21: 1}
Clients with >1 visit_id: 27502

==> Step counts by groups assigment:
process_step  confirm  start  step_1  step_2  step_3
Variation
Control         15326  23272   20029   18532   17307
Test            18612  26579   24185   22176   20805
Total           33938  49851   44214   40708   38112